# -*- coding: utf-8 -*-
"""project alprog sintaks Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-2EtKXcQyT6HzQxXNuf6L3Mivw-3tjf
"""

1*1